#!/bin/zsh

kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.0.0/deploy/static/provider/baremetal/deploy.yaml --force

#kubectl apply -f ingress-controller/ingress-service.yaml

kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission