#!/bin/zsh

kubectl create ns argocd 

kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

kubectl -n argocd patch deployment argocd-server --type json \
    -p='[ { "op": "replace", "path":"/spec/template/spec/containers/0/command","value": ["argocd-server","--insecure"] }]'

kubectl apply -f argocd/svc.yaml

#kubectl apply -f argocd/argocd-ingress.yaml


